### ISSUE TITLE
Add default filters for lower level variables.

### ISSUE THREAD

**Issue by nickbadlose** [JamesArthurHolland/ozone#4]
Hi! I was wondering if it would be possible to add filters to lower level variables. Like we currently can with the build variables.

For example, I have a runnable

```
  - name: my-runnable
    context_steps:
      - context: "{{MYCONTEXT}}"
        steps:
          - type: builtin
            name: bashScript
            with_vars:
              SCRIPT: script/my_script.sh
              MY_BOOL: "{{MY_BOOL}}"
```

I want to default `MY_BOOL` to `true`. Similar to how we do with build vars. `MY_BOOL: '{{MY_BOOL | default_if_none:"true" }}'`.
